import React from 'react';
import { Database, CheckCircle2, TrendingUp, HelpCircle, Layers, Activity } from 'lucide-react';
import { FidelityData } from '../types';

interface FidelityTabProps {
  fidelityData: FidelityData;
}

export const FidelityTab: React.FC<FidelityTabProps> = ({ fidelityData }) => {
  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div>
            <h2 className="text-base font-bold text-slate-100 flex items-center space-x-2">
              <Database className="w-5 h-5 text-blue-400" />
              <span>Synthetic Payment Stream Statistical Fidelity & Validation</span>
            </h2>
            <p className="text-xs text-slate-400">
              Rigorous distributional validation comparing synthetic transactions against empirical benchmark baselines.
            </p>
          </div>

          <div className="flex items-center space-x-2">
            <span className="text-xs font-mono text-slate-400">Composite Score:</span>
            <span className="px-3 py-1 bg-blue-950 border border-blue-800 text-blue-300 font-mono text-sm rounded-full font-bold">
              {fidelityData.fidelityScore.toFixed(1)} / 100
            </span>
          </div>
        </div>
      </div>

      {/* 4 Statistical Metrics Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        
        {/* Metric 1: Kolmogorov-Smirnov Distance */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-2">
          <div className="flex items-center justify-between text-slate-400 text-xs">
            <span>Kolmogorov-Smirnov (KS)</span>
            <Activity className="w-4 h-4 text-cyan-400" />
          </div>
          <div className="text-2xl font-black font-mono text-cyan-400">
            {fidelityData.ksDistanceAmount.toFixed(4)}
          </div>
          <div className="text-[11px] text-slate-400 font-mono">
            Amount distribution distance (p={fidelityData.ksPValueAmount.toFixed(4)})
          </div>
        </div>

        {/* Metric 2: 1D Wasserstein Distance */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-2">
          <div className="flex items-center justify-between text-slate-400 text-xs">
            <span>Wasserstein-1 Distance</span>
            <TrendingUp className="w-4 h-4 text-emerald-400" />
          </div>
          <div className="text-2xl font-black font-mono text-emerald-400">
            {fidelityData.wassersteinDistanceAmount.toFixed(4)}
          </div>
          <div className="text-[11px] text-slate-400 font-mono">
            Earth mover distance on log-normalized amount
          </div>
        </div>

        {/* Metric 3: Jensen-Shannon Divergence */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-2">
          <div className="flex items-center justify-between text-slate-400 text-xs">
            <span>Jensen-Shannon Divergence</span>
            <Layers className="w-4 h-4 text-amber-400" />
          </div>
          <div className="text-2xl font-black font-mono text-amber-400">
            {fidelityData.jensenShannonDivergence.toFixed(4)}
          </div>
          <div className="text-[11px] text-slate-400 font-mono">
            Symmetric probability divergence bound
          </div>
        </div>

        {/* Metric 4: Correlation Matrix Similarity */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-2">
          <div className="flex items-center justify-between text-slate-400 text-xs">
            <span>Correlation Similarity</span>
            <CheckCircle2 className="w-4 h-4 text-purple-400" />
          </div>
          <div className="text-2xl font-black font-mono text-purple-400">
            {fidelityData.correlationSimilarity.toFixed(1)}%
          </div>
          <div className="text-[11px] text-slate-400 font-mono">
            Frobenius norm correlation alignment
          </div>
        </div>

      </div>

      {/* Density Distribution Overlay Chart */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
          <div>
            <h3 className="text-sm font-bold text-slate-200">
              Empirical vs Synthetic Probability Density Function (Log-Amount)
            </h3>
            <p className="text-xs text-slate-400">
              Overlay comparing empirical payment distribution against synthesized stream generated by AegisPay Simulator
            </p>
          </div>
          <div className="flex items-center space-x-3 text-xs font-mono">
            <span className="flex items-center space-x-1">
              <span className="w-2.5 h-2.5 rounded-full bg-slate-500 inline-block"></span>
              <span className="text-slate-400">Empirical Reference</span>
            </span>
            <span className="flex items-center space-x-1">
              <span className="w-2.5 h-2.5 rounded-full bg-cyan-400 inline-block"></span>
              <span className="text-cyan-400">AegisPay Synthetic</span>
            </span>
          </div>
        </div>

        {/* SVG Density Bins Visual */}
        <div className="h-56 bg-slate-950 rounded-lg border border-slate-800 p-4 relative flex items-end justify-between px-6 sm:px-12">
          {fidelityData.densityCurve.bins.map((bin, idx) => {
            const refVal = fidelityData.densityCurve.reference[idx] || 10;
            const synVal = fidelityData.densityCurve.synthetic[idx] || 10;

            return (
              <div key={idx} className="flex flex-col items-center space-y-2 h-full justify-end z-10">
                <div className="flex items-end space-x-1.5 h-40">
                  <div
                    style={{ height: `${refVal}%` }}
                    className="w-4 bg-slate-600 rounded-t transition-all relative group"
                  >
                    <span className="opacity-0 group-hover:opacity-100 absolute -top-6 left-1/2 -translate-x-1/2 bg-slate-800 text-[10px] font-mono px-1 rounded text-slate-300 whitespace-nowrap z-20">
                      Ref: {refVal}%
                    </span>
                  </div>
                  <div
                    style={{ height: `${synVal}%` }}
                    className="w-4 bg-cyan-500 rounded-t transition-all relative group shadow-lg shadow-cyan-500/30"
                  >
                    <span className="opacity-0 group-hover:opacity-100 absolute -top-6 left-1/2 -translate-x-1/2 bg-cyan-900 text-[10px] font-mono px-1 rounded text-cyan-200 whitespace-nowrap z-20">
                      Syn: {synVal}%
                    </span>
                  </div>
                </div>
                <span className="text-[10px] font-mono text-slate-500">${Math.round(Math.exp(bin))}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* Transparent Formula Breakdown Box */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-2 text-xs font-mono">
        <div className="flex items-center space-x-2 text-slate-200 font-bold">
          <HelpCircle className="w-4 h-4 text-cyan-400" />
          <span>Fidelity Scoring Methodology</span>
        </div>
        <p className="text-slate-400">
          Composite synthetic fidelity is calculated with an open, non-fabricated formula:
        </p>
        <div className="p-3 bg-slate-950 border border-slate-800 rounded text-cyan-300 text-[11px] overflow-x-auto">
          {fidelityData.formula_description}
        </div>
      </div>

    </div>
  );
};
